<a href="https://colab.research.google.com/github/HyeongseokKim/My_codes/blob/main/KNN%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_wine

In [ ]:
import pandas as pd
data_wine=load_wine()

In [ ]:
wine_df=pd.DataFrame(data_wine.data ,columns=data_wine.feature_names)

In [ ]:
wine_df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [49]:
import numpy as np
def euclidean_distance(a,b):
  dist=np.sqrt(np.sum((a-b)**2))
  return dist

In [50]:
dist_lst=[]
d_result=[]
for i in range(len(wine_df)):
  dist_lst=[]
  for j in range(len(wine_df)):
    base_point = wine_df.iloc[i].values
    target_point = wine_df.iloc[j].values
    w_dist=euclidean_distance(base_point, target_point)
    dist_lst.append(w_dist)
  d_result.append(dist_lst)

In [57]:
pd.DataFrame(d_result)

,0,1,2,3,4,5,6,7,8,9,...,168,169,170,171,172,173,174,175,176,177
0,0.000000,31.265012,122.831154,415.245400,330.174500,385.295960,227.129474,230.091599,36.116966,35.274977,...,315.927567,435.392211,555.895155,596.455105,406.657723,326.660049,316.110527,230.240023,225.215184,506.059368
1,31.265012,0.000000,135.224693,430.251561,315.668800,400.210294,240.063413,245.984974,6.786383,7.832918,...,300.381312,420.435462,540.084013,580.264085,390.251934,310.236117,300.274500,216.221232,211.213539,490.235268
2,122.831154,135.224693,0.000000,295.262711,450.331053,265.256948,105.211462,111.827681,140.149239,140.074677,...,435.081395,555.167072,675.031791,715.182277,525.125384,445.076785,435.042939,350.571188,345.562652,625.070178
3,415.245400,430.251561,295.262711,0.000000,745.039443,30.091969,190.796230,185.204752,435.313485,435.261604,...,730.096273,850.053083,970.167815,1010.378276,820.313787,740.249375,730.123558,645.068999,640.062584,920.201042
4,330.174500,315.668800,450.331053,745.039443,0.000000,715.054595,555.475848,560.020404,310.797076,310.702995,...,20.776525,105.374945,226.110051,267.007579,79.951032,24.149259,22.421559,100.252529,105.178310,176.506783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,326.660049,310.236117,445.076785,740.249375,24.149259,710.243537,550.059368,555.641007,305.129660,305.098827,...,15.058277,111.407215,230.038220,270.182659,80.189533,0.000000,12.599016,98.278931,103.139001,180.061597
174,316.110527,300.274500,435.042939,730.123558,22.421559,700.126878,540.114851,545.373047,295.213194,295.141088,...,3.885010,120.442447,240.121611,280.497059,90.765480,12.599016,0.000000,86.986640,91.863273,190.112044
175,230.240023,216.221232,350.571188,645.068999,100.252529,615.096394,455.708917,460.051328,211.443705,211.258675,...,86.463487,205.226250,325.925482,366.586616,177.398611,98.278931,86.986640,0.000000,5.358890,276.086015
176,225.215184,211.213539,345.562652,640.062584,105.178310,610.087927,450.701703,455.037650,206.444162,206.260421,...,91.356684,210.224750,330.897825,371.561019,182.324504,103.139001,91.863273,5.358890,0.000000,281.068992
177,506.059368,490.235268,625.070178,920.201042,176.506783,890.204837,730.086700,735.476864,485.146226,485.101981,...,190.221674,71.818033,50.499153,90.727539,100.241088,180.061597,190.112044,276.086015,281.068992,0.000000

In [54]:
def cos_simularity(a,b):
  cos=np.sum(a*b) / (np.sqrt(np.sum(a**2))*np.sqrt(np.sum(b**2)))
  return cos

In [59]:
cos_lst=[]
c_result=[]
for i in range(len(wine_df)):
  cos_lst=[]
  for j in range(len(wine_df)):
    base_point = wine_df.iloc[i].values
    target_point = wine_df.iloc[j].values
    cos_sim=cos_simularity(base_point, target_point)
    cos_lst.append(cos_sim)
  c_result.append(cos_lst)

In [60]:
pd.DataFrame(c_result)

,0,1,2,3,4,5,6,7,8,9,...,168,169,170,171,172,173,174,175,176,177
0,1.000000,0.999709,0.999430,0.999085,0.999073,0.999118,0.999005,0.999668,0.999657,0.999681,...,0.999599,0.997983,0.997411,0.997499,0.999632,0.999829,0.999710,0.999633,0.999666,0.998142
1,0.999709,1.000000,0.999936,0.999819,0.997764,0.999835,0.999785,0.999992,0.999991,0.999984,...,0.998745,0.996227,0.995426,0.995605,0.998831,0.999267,0.998959,0.998728,0.998783,0.996509
2,0.999430,0.999936,1.000000,0.999950,0.997147,0.999953,0.999932,0.999963,0.999964,0.999959,...,0.998352,0.995500,0.994581,0.994833,0.998443,0.998961,0.998594,0.998259,0.998321,0.995861
3,0.999085,0.999819,0.999950,1.000000,0.996378,0.999999,0.999996,0.999852,0.999854,0.999834,...,0.997746,0.994535,0.993534,0.993814,0.997862,0.998473,0.998030,0.997662,0.997732,0.994929
4,0.999073,0.997764,0.997147,0.996378,1.000000,0.996434,0.996225,0.997681,0.997660,0.997746,...,0.999768,0.999758,0.999568,0.999527,0.999703,0.999478,0.999694,0.999822,0.999815,0.999744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0.999829,0.999267,0.998961,0.998473,0.999478,0.998501,0.998378,0.999239,0.999239,0.999299,...,0.999913,0.998761,0.998242,0.998401,0.999933,1.000000,0.999964,0.999871,0.999877,0.998953
174,0.999710,0.998959,0.998594,0.998030,0.999694,0.998062,0.997920,0.998928,0.998921,0.998993,...,0.999987,0.999118,0.998669,0.998795,0.999979,0.999964,1.000000,0.999944,0.999948,0.999270
175,0.999633,0.998728,0.998259,0.997662,0.999822,0.997705,0.997532,0.998668,0.998653,0.998725,...,0.999951,0.999312,0.998945,0.999023,0.999944,0.999871,0.999944,1.000000,0.999997,0.999390
176,0.999666,0.998783,0.998321,0.997732,0.999815,0.997776,0.997605,0.998725,0.998708,0.998779,...,0.999954,0.999273,0.998903,0.998974,0.999943,0.999877,0.999948,0.999997,1.000000,0.999352
177,0.998142,0.996509,0.995861,0.994929,0.999744,0.994976,0.994755,0.996439,0.996441,0.996576,...,0.999428,0.999960,0.999828,0.999919,0.999364,0.998953,0.999270,0.999390,0.999352,1.000000